function Input_Panel()
%   This function creates the input menu bar
global Orbital
Orbital.InputPanel = ...
    uipanel(...
    'Parent', Orbital.Figure, ...
    'Units', 'normalized', ...
    'Title', 'Input', ...
    'TitlePosition','lefttop',...
    'BackgroundColor','w',...
    'ForegroundColor','k',...
    'BorderType','etchedout',...
    'FontSize',10,...
    'FontWeight','bold',...
    'Position', [0.02,0.41,0.2,0.57] ...
    );

Orbital.InputTab_group = ...
    uitabgroup(...
    'Parent',Orbital.InputPanel,...
    'TabLocation', 'left'...
    );

Orbital.InputBCs_tab = ...
    uitab(...
    Orbital.InputTab_group,...
    'title', 'BCs',...
    'ForeGroundColor', 'b',...
    'BackgroundColor', 'w'...
    );
BCs_tab();
Orbital.InputInit_tab = ...
    uitab(...
    Orbital.InputTab_group,...
    'title', 'ICs',...
    'ForeGroundColor', 'b',...
    'BackgroundColor', 'w'...
    );



    function ICs_tab()

    end
    function BCs_tab()
        %   Creates items in BCs tab

        %   Radius Magnitude Options
        Orbital.Rmagtxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('R Magnitude'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.95, 0.5, 0.04] ...
            );
        
        Orbital.Rmag = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.9, 0.7, 0.04] ...
            );
        Orbital.Rmag_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(1)},...
            'Position', [0.85, 0.95, 0.1, 0.04] ...
            );
        
        %   Velocity Magnitude Options
        
        Orbital.Vmagtxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('V Magnitude'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.85, 0.5, 0.04] ...
            );
        
        Orbital.Vmag = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.8 0.7, 0.04] ...
            );
        Orbital.Vmag_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(2)},...
            'Position', [0.85, 0.85, 0.1, 0.04] ...
            );
        
        
        %   Energy Options
        
        Orbital.energytxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Energy'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.75, 0.5, 0.04] ...
            );
        
        Orbital.energy = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.7 0.7, 0.04] ...
            );
        Orbital.energy_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(3)},...
            'Position', [0.85, 0.75, 0.1, 0.04] ...
            );
        
        
        %   Semi-Major Axis Options
        
        Orbital.atxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Semi-Major Axis'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.75, 0.6, 0.04] ...
            );
        
        Orbital.a = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.7 0.7, 0.04] ...
            );
        Orbital.a_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(4)},...
            'Position', [0.85, 0.75, 0.1, 0.04] ...
            );
        
        %   Eccentricity Options
        
        Orbital.etxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Eccentricity'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.65, 0.5, 0.04] ...
            );
        
        Orbital.e = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '0-1', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.6, 0.7, 0.04] ...
            );
        Orbital.e_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(5)},...
            'Position', [0.85, 0.65, 0.1, 0.04] ...
            );
        
        %   Inclination Options
        
        Orbital.itxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Inclination'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.55, 0.5, 0.04] ...
            );
        
        Orbital.i = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[degrees]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.5, 0.7, 0.04] ...
            );
        Orbital.i_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(6)},...
            'Position', [0.85, 0.55, 0.1, 0.04] ...
            );
        
        %   Inclination Options
        
        Orbital.Ttxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Time Period'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.45, 0.5, 0.04] ...
            );
        
        Orbital.T = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'w',...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.4, 0.7, 0.04] ...
            );
        Orbital.T_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'w',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(7)},...
            'Position', [0.85, 0.45, 0.1, 0.04] ...
            );
        
    end

    function BC_CB_cb(num)

        Order = {'Rmag','Vmag','energy','a','e','i','T'};
        Order2 = {'Rmag_act','Vmag_act','energy_act','a_act','e_act','i_act','T_act'};
        BC = Order{num};
        Act = Order2{num};
        
        Val = get(eval(sprintf('Orbital.%s',Act)),'Value');
        if Val == 1
            set(eval(sprintf('Orbital.%s',BC)),'enable','on');
            Orbital.setBC_Ind(num) = 1;
        else
            set(eval(sprintf('Orbital.%s',BC)),'enable','off');
            Orbital.setBC_Ind(num) = 0;
        end
    end
end