function Input_Panel2()
%   This function creates the input menu bar
global Orbital
Orbital.FinBurn = 0;
Orbital.setFVs_Ind = zeros(7,1);
Orbital.setBCs_Ind = zeros(6,1);
Orbital.InType = 1;
% Orbital.InputPanel = ...
%     uipanel(...
%     'Parent', Orbital.Figure, ...
%     'Units', 'normalized', ...
%     'Title', 'Input', ...
%     'TitlePosition','lefttop',...
%     'BackgroundColor','k',...
%     'ForegroundColor','w',...
%     'BorderType','etchedout',...
%     'FontSize',10,...
%     'FontWeight','bold',...
%     'Position', [0.02,0.11,0.2,0.87] ...
%     );


Orbital.InputICs_tab = ...
    uitab(...
    Orbital.InputTab_group,...
    'title', sprintf('ICs'),...
    'ForegroundColor', 'k'...
    );

Orbital.InputBCs_tab = ...
    uitab(...
    Orbital.InputTab_group,...
    'title', sprintf('BCs'),...
    'ForegroundColor', 'k'...
    );

Orbital.InputTab2_group = ...
    uitabgroup(...
    'Parent',Orbital.InputICs_tab,...
    'Units','Normalized', ...
    'Position',[0,0.85,1,0.15],...
    'TabLocation', 'top'...
    );
Orbital.InputRV_tab = ...
    uitab(...
    Orbital.InputTab2_group,...
    'title', 'R and V',...
    'ButtonDownFcn', {@(hObject,eventdata) Input_type(1)},...
    'ForeGroundColor', 'k'...
    );
% uicontrol(Orbital.InputRV_tab, 'Callback',{@(hObject,eventdata) Input_type(1)});
Orbital.InputCOEs_tab = ...
    uitab(...
    Orbital.InputTab2_group,...
    'title', 'COEs',...
    'ButtonDownFcn', {@(hObject,eventdata) Input_type(2)},...
    'ForeGroundColor', 'k'...
    );
BCs_tab();
FVs_tab();
RVs_tab();
COEs_tab();
%--------------------------------------------------------------------------    
%                           INITIAL CONDITIONS
%--------------------------------------------------------------------------
    function RVs_tab()
        %   Initial Position Vector
        Orbital.R0txt = ...
            uicontrol(...
            'Parent', Orbital.InputRV_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Radius'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left',...
            'ForegroundColor', 'k', ...
            'Position', [0.02, 0.6, 0.3, 0.25] ...
            );
        
        Orbital.R0 = ...
            uicontrol(...
            'Parent', Orbital.InputRV_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[Rx Ry Rz](km)', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.32, 0.55, 0.67, 0.35] ...
            );
        
        %   Initial Velocity Vector
        Orbital.V0txt = ...
            uicontrol(...
            'Parent', Orbital.InputRV_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Velocity'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left',...
            'ForegroundColor', 'k', ...
            'Position', [0.02, 0.15, 0.3, 0.25] ...
            );
        
        Orbital.V0 = ...
            uicontrol(...
            'Parent', Orbital.InputRV_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[Vx Vy Vz] (km/s)', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.32, 0.1, 0.67, 0.35] ...
            );
    end



    function COEs_tab()
        %   Input Tab for the 6 orbital elements
        %   [a,e,inc,RAAN,om,anom]
        
        %   Input for Semi Major Axis
        Orbital.atxt = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('a'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment','left',...
            'ForegroundColor', 'k', ...
            'Position', [0.02, 0.75, 0.1, 0.2] ...
            );
        
        Orbital.a_in = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km/s]', ...
            'FontSize', 7, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.1, 0.68, 0.33, 0.25] ...
            );
        
        
        
        %   Input for Eccentricity
        Orbital.etxt = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('e'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment','left',...
            'ForegroundColor', 'k', ...
            'Position', [0.55, 0.75, 0.1, 0.2] ...
            );
        
        Orbital.e_in = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[0-1]', ...
            'FontSize', 7, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.65, 0.68, 0.33, 0.25] ...
            );
        
        
        %   Input for Inclination
        Orbital.inctxt = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('i'), ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment','left',...
            'ForegroundColor', 'k', ...
            'Position', [0.02, 0.45, 0.1, 0.2] ...
            );
        
        Orbital.inc = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 7, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.1, 0.35, 0.33, 0.25] ...
            );
        
        %   Input for Right Ascension of Ascending Node

        
        Orbital.RAANtxt = ...
            axes(...
            'Parent', Orbital.InputCOEs_tab,...
            'Units', 'normalized', ...
            'Color', 'k',...
            'Position', [0.55, 0.45, 0.1, 0.2] ...
            );
        axis off; grid off;
        text(0, 0.5, sprintf('\\Omega'), 'FontWeight','bold',...
            'Color','k','Parent', Orbital.RAANtxt);
        
        Orbital.RAAN = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 7, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.65, 0.35, 0.33, 0.25] ...
            );
        
        
        
        %   Input for om

        
        Orbital.omtxt = ...
            axes(...
            'Parent', Orbital.InputCOEs_tab,...
            'Units', 'normalized', ...
            'Color', 'k',...
            'Position', [0.01, 0.07, 0.1, 0.2] ...
            );
        axis off; grid off;
        text(0, 0.5, sprintf('\\omega'), 'FontWeight','bold',...
            'Color','k','Parent', Orbital.omtxt);
        
        Orbital.om = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.1, 0.02, 0.33, 0.25] ...
            );
        
    %   Input for True Anomaly

        
        Orbital.anomtxt = ...
            axes(...
            'Parent', Orbital.InputCOEs_tab,...
            'Units', 'normalized', ...
            'Color', 'k',...
            'Position', [0.55, 0.07, 0.1, 0.2] ...
            );
        axis off; grid off;
        text(0, 0.5, sprintf('\\theta'), 'FontWeight','bold',...
            'Color','k','Parent', Orbital.anomtxt);
        
        Orbital.anom = ...
            uicontrol(...
            'Parent', Orbital.InputCOEs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.65, 0.02, 0.33, 0.25] ...
            );
    end


%--------------------------------------------------------------------------    
%                           FREE VARIABLES
%--------------------------------------------------------------------------

    function FVs_tab()
        
        
        
        %   Add Text explaining what should be done
        Orbital.FVs_exp = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style', 'text', ...
            'units', 'normalized', ...
            'String', sprintf(['Please tick the checkbox parallel to ', ...
            'the boundary condition you would like to constrain',...
            'and enter the initial guess for the free variables.']),...
            'Position', [ 0.01, 0.76, 0.98,0.075],...
            'FontSize', 7,...
            'FontWeight', 'bold',...
            'ForegroundColor', 'k'...
            );
            
    
        
        %   Creates items in BCs tab

        %   First DeltaV Burn
        Orbital.dV1txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('dV Magnitude 1'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'HorizontalAlignment', 'Left',...
            'Position', [0.03, 0.71, 0.98, 0.03] ...
            );
        
        Orbital.dV1 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km/s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.68, 0.8, 0.03] ...
            );
        Orbital.dV1_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(1)},...
            'Position', [0.85, 0.68, 0.1, 0.03] ...
            );
        
        
        %   Flight Path Angle in first maneuver
        Orbital.FPA1txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Flight Path Angle 1'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'HorizontalAlignment', 'Left',...
            'Position', [0.01, 0.63, 0.7, 0.03] ...
            );
        
        Orbital.FPA1 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.6, 0.8, 0.03] ...
            );
        Orbital.FPA1_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(2)},...
            'Position', [0.85, 0.6, 0.1, 0.03] ...
            );
        
        %   Out of plane angle of deltaV1
        
        Orbital.delta1txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Delta Burn Angle 1'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.55, 0.7, 0.03] ...
            );
        
        Orbital.delta1 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.52, 0.8, 0.03] ...
            );
        Orbital.delta1_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(3)},...
            'Position', [0.85, 0.52, 0.1, 0.03] ...
            );
        
        
        %   Time of Flight
        
        Orbital.TOFtxt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Time of Flight'), ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'Left',...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.47 0.5, 0.03] ...
            );
        
        Orbital.TOF = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.44, 0.8, 0.03] ...
            );
        Orbital.TOF_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(4)},...
            'Position', [0.85, 0.44, 0.1, 0.03] ...
            );
        
        
        %   Second dV Magnitude
        
        Orbital.dV2txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('dV Magnitude 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.39, 0.6, 0.03] ...
            );
        
        Orbital.dV2 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km/s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.36, 0.8, 0.03] ...
            );
        Orbital.dV2_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(5)},...
            'Position', [0.85, 0.36, 0.1, 0.03] ...
            );
        
        
        %   Flight Path Angle of Second Burn
        
        Orbital.FPA2txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Flight Path Angle 2'), ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'Left',...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.31, 0.98, 0.03] ...
            );
        
        Orbital.FPA2 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.28, 0.8, 0.03] ...
            );
        Orbital.FPA2_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(6)},...
            'Position', [0.85, 0.28, 0.1, 0.03] ...
            );
        
        %   Delta angle (out of plane) of second burn
        
        Orbital.delta2txt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Delta Burn Angle 2'), ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'Left',...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.23, 0.7, 0.03] ...
            );
        
        Orbital.delta2 = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','on',...
            'Position', [0.01, 0.2, 0.8, 0.03] ...
            );
        Orbital.delta2_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)FV_CB_cb(7)},...
            'Position', [0.85, 0.2, 0.1, 0.03] ...
            );
        %---------------------------------------------------------------
        %       FINITE BURN OPTIONS
        %---------------------------------------------------------------
        
        %   Activate Finite Burn Options
        Orbital.FinBurntxt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Tick Checkbox to Activate Finite Burn Options'), ...
            'FontSize', 7.5, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.12, 0.8, 0.07] ...
            );
        Orbital.FinBurn_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'enable','off',...
            'Callback',{@(hObject,eventdata)FV_CB_cb(10)},...
            'Position', [0.85, 0.14, 0.1, 0.05] ...
            );
        
        %   Rate of Mass Change
        
        Orbital.mdottxt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Rate of Mass Change'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.105, 0.98, 0.03] ...
            );
        
        Orbital.mdot = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[kg/s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.075, 0.8, 0.03] ...
            );
        Orbital.mdot_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'enable','off',...
            'Callback',{@(hObject,eventdata)FV_CB_cb(8)},...
            'Position', [0.85, 0.075, 0.1, 0.03] ...
            );
        
        %   Duration of Impulse
        
        Orbital.tBurntxt = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Duration of Burn'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.01, 0.04, 0.98, 0.03] ...
            );
        
        Orbital.tBurn = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.01, 0.8, 0.03] ...
            );
        Orbital.tBurn_act = ...
            uicontrol(...
            'Parent', Orbital.InputICs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'enable','off',...
            'Callback',{@(hObject,eventdata)FV_CB_cb(9)},...
            'Position', [0.85, 0.01, 0.1, 0.03] ...
            );

    end



%--------------------------------------------------------------------------    
%                           BOUNDARY CONDITIONS
%--------------------------------------------------------------------------
    function BCs_tab()
%   Add Text explaining what should be done
        Orbital.BCs_exp = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style', 'text', ...
            'units', 'normalized', ...
            'String', sprintf(['Please tick the checkbox parallel to ', ...
            'the boundary condition you would like to set']),...
            'Position', [ 0.01, 0.93, 0.98,0.06],...
            'FontSize', 7,...
            'FontWeight','bold',...
            'ForegroundColor', 'k'...
            );
            
    
        
        %   Creates items in BCs tab

        %   Radius Magnitude Options
        Orbital.Rmagtxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('R Magnitude'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.89, 0.96, 0.025] ...
            );
        
        Orbital.Rmag = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.86, 0.8, 0.025] ...
            );
        Orbital.Rmag_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(1)},...
            'Position', [0.85, 0.86, 0.1, 0.025] ...
            );
        
        %   Velocity Magnitude Options
        
        Orbital.Vmagtxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('V Magnitude'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.83, 0.95, 0.025] ...
            );
        
        Orbital.Vmag = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.8, 0.8, 0.025] ...
            );
        Orbital.Vmag_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(2)},...
            'Position', [0.85, 0.8, 0.1, 0.025] ...
            );
        
        
        %   Energy Options
        
        Orbital.energytxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Energy'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.77, 0.95, 0.025] ...
            );
        
        Orbital.energy = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.74, 0.8, 0.025] ...
            );
        Orbital.energy_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(3)},...
            'Position', [0.85, 0.74, 0.1, 0.025] ...
            );
        
        
        %   Semi-Major Axis Options
        
        Orbital.atxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Semi-Major Axis'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.71, 0.95, 0.025] ...
            );
        
        Orbital.a = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.68, 0.8, 0.025] ...
            );
        Orbital.a_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(4)},...
            'Position', [0.85, 0.68, 0.8, 0.025] ...
            );
        
        %   Eccentricity Options
        
        Orbital.etxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Eccentricity'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.65, 0.95, 0.025] ...
            );
        
        Orbital.e = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '0-1', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.62, 0.8, 0.025] ...
            );
        Orbital.e_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(5)},...
            'Position', [0.85, 0.62, 0.1, 0.025] ...
            );
        
        %   Inclination Options
        
        Orbital.itxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Inclination'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.59, 0.95, 0.025] ...
            );
        
        Orbital.i = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.56, 0.8, 0.025] ...
            );
        Orbital.i_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(6)},...
            'Position', [0.85, 0.56, 0.1, 0.025] ...
            );
        
        %   Time Period Options
        
        Orbital.Ttxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Time Period'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.53, 0.95, 0.025] ...
            );
        
        Orbital.T = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.5, 0.8, 0.025] ...
            );
        Orbital.T_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Callback',{@(hObject,eventdata)BC_CB_cb(13)},...
            'Position', [0.85, 0.5, 0.1, 0.025] ...
            );
%--------------------------------------------------------------------------    
%                           TOLERANCE
    
        Orbital.toltxt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Error Tolerance'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'Left',...
            'ForegroundColor', 'k', ...
            'Position', [0.03, 0.43, 0.95, 0.025] ...
            );
        
        Orbital.tol = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '1e-3', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', 'k', ...
            'Enable','off',...
            'Position', [0.01, 0.4, 0.8, 0.025] ...
            );
        Orbital.tol_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'Visible', 'on',...
            'Callback',{@(hObject,eventdata)tolact_cb()},...
            'Position', [0.85, 0.4, 0.1, 0.025] ...
            );
        function tolact_cb()
            val = get(Orbital.tol_act,'Value');
            if val == 1
                set(Orbital.tol,'enable','on');
            else
                set(Orbital.tol,'enable','off');
            end
        end
            
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%{
        %   Radius Magnitude Options
        Orbital.Rmag2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('R Magnitude 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.4, 0.5, 0.025] ...
            );
        
        Orbital.Rmag2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.37, 0.7, 0.025] ...
            );
        Orbital.Rmag2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(7)},...
            'Position', [0.85, 0.4, 0.1, 0.025] ...
            );
        
        %   Velocity Magnitude Options
        
        Orbital.Vmag2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('V Magnitude 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.34, 0.5, 0.025] ...
            );
        
        Orbital.Vmag2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.31, 0.7, 0.025] ...
            );
        Orbital.Vmag2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(8)},...
            'Position', [0.85, 0.34, 0.1, 0.025] ...
            );
        
        
        %   Energy Options
        
        Orbital.energy2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Energy 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.28, 0.5, 0.025] ...
            );
        
        Orbital.energy2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.25, 0.7, 0.025] ...
            );
        Orbital.energy2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(9)},...
            'Position', [0.85, 0.28, 0.1, 0.025] ...
            );
        
        
        %   Semi-Major Axis Options
        
        Orbital.a2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Semi-Major Axis 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.22, 0.6, 0.025] ...
            );
        
        Orbital.a2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[km]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.19 0.7, 0.025] ...
            );
        Orbital.a2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(10)},...
            'Position', [0.85, 0.22, 0.1, 0.025] ...
            );
        
        %   Eccentricity Options
        
        Orbital.e2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Eccentricity 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.16, 0.5, 0.025] ...
            );
        
        Orbital.e2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '0-1', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.13, 0.7, 0.025] ...
            );
        Orbital.e2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(11)},...
            'Position', [0.85, 0.16, 0.1, 0.025] ...
            );
        
        %   Inclination Options
        
        Orbital.i2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', 'Inclination 2', ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.1, 0.5, 0.025] ...
            );
        
        Orbital.i2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[rad]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.07, 0.7, 0.025] ...
            );
        Orbital.i2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(12)},...
            'Position', [0.85, 0.1, 0.1, 0.025] ...
            );
        
        %   Inclination Options
        
        Orbital.T2txt = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','text', ...
            'Units', 'normalized', ...
            'String', sprintf('Time Period 2'), ...
            'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Position', [0.01, 0.04, 0.5, 0.025] ...
            );
        
        Orbital.T2 = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','edit', ...
            'Units', 'normalized', ...
            'String', '[s]', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', 'k',...
            'ForegroundColor', 'w', ...
            'Enable','off',...
            'Position', [0.01, 0.01, 0.7, 0.025] ...
            );
        Orbital.T2_act = ...
            uicontrol(...
            'Parent', Orbital.InputBCs_tab,...
            'Style','CheckBox', ...
            'Units', 'normalized', ...
            'BackgroundColor', 'k',...
            'Callback',{@(hObject,eventdata)BC_CB_cb(14)},...
            'Position', [0.85, 0.04, 0.1, 0.025] ...
            );
%}
        
    end




%--------------------------------------------------------------------------    
%                           CALLBACK FUNCTIONS
%--------------------------------------------------------------------------   

    function Input_type(opt)
       
        Orbital.InType = opt;
      
    end

    function BC_CB_cb(num)
        
        Order = {'Rmag','Vmag','energy','a','e','i',...
            'Rmag2','Vmag2','energy2','a2','e2','i2',...
            'T', 'T2'};
        Order2 = strcat(Order,'_act');
        BC = Order{num};
        Act = Order2{num};
        Val = get(eval(sprintf('Orbital.%s',Act)),'Value');
        
        
        
        if Val == 1
                set(eval(sprintf('Orbital.%s',BC)),'enable','on');
                Orbital.setBCs_Ind(num) = 1;
          
        else

            set(eval(sprintf('Orbital.%s',BC)),'enable','off');
            Orbital.setBCs_Ind(num) = 0;

        end
    end


    

    function FV_CB_cb(num)
         
        if num == 10
            Val = get(Orbital.FinBurn_act,'Value');
            if Val == 1
                set(Orbital.mdot,'Enable','on');
                set(Orbital.tBurn,'Enable','on');
                Orbital.FinBurn = 1;
            else
                set(Orbital.mdot,'Enable','off');
                set(Orbital.tBurn,'Enable','off');
                Orbital.FinBurn = 0;
            end
        else
            Order = {'dV1','FPA1','delta1','TOF','dV2','FPA2','delta2',...
                'mdot','tBurn'};

            Order2 = strcat(Order,'_act');
    %         BC = Order{num};
            Act = Order2{num};

            Val = get(eval(sprintf('Orbital.%s',Act)),'Value');
            if Val == 1
    %             set(eval(sprintf('Orbital.%s',BC)),'enable','on');
                Orbital.setFVs_Ind(num) = 1;
            else
    %             set(eval(sprintf('Orbital.%s',BC)),'enable','off');
                Orbital.setFVs_Ind(num) = 0;
            end
        end
    end
end
