function Output_Panel()
%   Create Output GUI Options
global Orbital

%         plot_visual2(Orbital.ThreeDAxes);

% ResultsTab_group
Orbital.NewBCs_tab = ...
    uitab(...
    Orbital.ResultsTab_group,...
    'title', sprintf('Results'),...
    'ForegroundColor', 'b'...
    );

Orbital.NewGuess_tab = ...
    uitab(...
    Orbital.ResultsTab_group,...
    'title', sprintf('Solution Guess'),...
    'ForegroundColor', 'b',...
    'BackgroundColor', 'k'...
    );
    Output_tables()
    
    function Output_tables()
        
        %   Output results obtained to table
        
        %   Current Solution Obtained
        BC_Names = {'Radius Magniude (km)','Velocity Magnitude (km/s)','Energy','Semi-Major Axis (km)',...
            'Eccentricity','Inclination (deg)','Period (s)','Error'};
        Orbital.SolTable = ...
            uitable(...
            'Parent',Orbital.NewBCs_tab,...
            'Units','Normalized',...
            'Position', [0.01,0.2,0.98,0.78],...
            'ColumnName', BC_Names...
            );
         Orbital.FinalSol = ...
             uicontrol(...
             'Parent', Orbital.NewBCs_tab,...
             'Units', 'Normalized', ...
             'Style','text',...
             'Position', [0.02,0.03,0.98,0.13],...
             'FontWeight', 'bold',...
             'FontSize', 10,...
             'ForegroundColor', 'k', ...
             'HorizontalAlignment', 'left',...
             'String',sprintf('Loading...')...
             );
             
        
        Guess_Names = {'delta V1', 'FPA1', 'delta1', 'TOF','delta V2','FPA2','delta2'};
        Orbital.GuessTable = ...
            uitable(...
            'Parent',Orbital.NewGuess_tab,...
            'Units','Normalized',...
            'Position', [0.01,0.2,0.98,0.78],...
            'ColumnName', Guess_Names...
            );
         
        Orbital.FinalGuess = ...
             uicontrol(...
             'Parent', Orbital.NewGuess_tab,...
             'Units', 'Normalized', ...
             'Style','text',...
             'Position', [0.02,0.03,0.98,0.13],...
             'FontWeight', 'bold',...
             'FontSize', 10,...
             'ForegroundColor', 'k', ...
             'HorizontalAlignment', 'left',...
             'String',sprintf('Wait for what The Rock is cooking...')...
             );
        
    end

end